### ISSUE TITLE
Processes hang on FreeBSD/i386 after fd484be 

### ISSUE THREAD

**Issue by emaste** [libcxxrt/libcxxrt#15]
https://lists.freebsd.org/archives/dev-commits-src-all/2022-March/008441.html
> After this merge [of upstream libcxxrt],  some i386 c++ processes are hanging.

@DimitryAndric writes:
> I could reproduce a CMake hang with poppler-qt5, and it turns out that
> libcxxrt's https://github.com/libcxxrt/libcxxrt/commit/fd484be can make __cxa_guard_acquire hang on i386.

**Comment by davidchisnall** [comment]
Do you know the state of the lock word when it hangs?  It's likely that I got the guard word wrong for little-endian 32-bit platforms.  Can you take a look at `class DoubleWordGuard` and, in particular, the values that it's instantiated with on lines 295 and 300 of guard.cc?  If these don't have the same layout that the compiler expects then it will deadlock.

**Comment by jrtc27** [comment]
My guess relayed to dim on IRC is https://github.com/libcxxrt/libcxxrt/blob/master/src/guard.cc#L230 should be storing 0 not initialised to the lock word; that's certainly wrong, and I could picture how that could lead to deadlock

**Comment by davidchisnall** [comment]
Yes, I think you're right.  That should be releasing the lock, which is done by storing 0.  Without that, the lock is left held and so the next time the guard is hit the caller will deadlock.  Can you test it and raise a PR if it fixes the issue?

**Comment by DimitryAndric** [comment]
So in a hanging situation, I have this:

```
Thread 2 (LWP 125226 of process 58270):
#0  sched_yield () at sched_yield.S:4
#1  0x20de0fde in __cxa_guard_acquire (guard_object=0x20dd2f34) at /usr/src/contrib/libcxxrt/guard.cc:341
#2  0x20dc5c83 in std::__1::__thread_local_data () at /usr/src/contrib/llvm-project/libcxx/src/thread.cpp:117
#3  0x007b3dfb in ?? ()
#4  0x20cf16e9 in thread_start (curthread=0x21724a00) at /usr/src/lib/libthr/thread/thr_create.c:292
#5  0x00000000 in ?? ()

Thread 1 (LWP 100227 of process 58270):
#0  _umtx_op_err () at /usr/src/lib/libthr/arch/i386/i386/_umtx_op_err.S:39
#1  0x20cff5d4 in _thr_umtx_wait (mtx=0x21724a00, id=125226, timeout=0x0) at /usr/src/lib/libthr/thread/thr_umtx.c:201
#2  0x20cf376b in join_common (pthread=0x21724a00, thread_return=0x0, abstime=0x0, peek=<optimized out>) at /usr/src/lib/libthr/thread/thr_join.c:147
#3  0x20cf346f in _thr_join (pthread=0x21724a00, thread_return=0x0) at /usr/src/lib/libthr/thread/thr_join.c:62
#4  0x20dc5ae2 in std::__1::__libcpp_thread_join (__t=<optimized out>) at /usr/src/contrib/llvm-project/libcxx/include/__threading_support:534
#5  std::__1::thread::join (this=0x217808b4) at /usr/src/contrib/llvm-project/libcxx/src/thread.cpp:48
#6  0x007b3b90 in ?? ()
#7  0x007b1da2 in ?? ()
#8  0x20c902cb in ?? () from /usr/local/lib/libuv.so.1
#9  0x20ca197f in ?? () from /usr/local/lib/libuv.so.1
#10 0x20c907d7 in uv_run () from /usr/local/lib/libuv.so.1
#11 0x007b2241 in ?? ()
#12 0x0072a788 in ?? ()
#13 0x00744608 in ?? ()
#14 0x00724580 in ?? ()
#15 0x0059dde9 in ?? ()
#16 0x0058f351 in ?? ()
#17 0x0058bd1d in ?? ()
#18 0x0058be80 in ?? ()
#19 0x00000000 in ?? ()

(gdb) thread 2
[Switching to thread 2 (LWP 125226 of process 58270)]
#0  sched_yield () at sched_yield.S:4
4       sched_yield.S: No such file or directory.

(gdb) up
#1  0x20de0fde in __cxa_guard_acquire (guard_object=0x20dd2f34) at /usr/src/contrib/libcxxrt/guard.cc:341

(gdb) print *guard_object
$3 = {static locked = 2147483648, static initialised = 1, init_word = {val = 1}, lock_word = {val = 1}}
```

E.g., we're at the end of the `__cxa_guard_acquire` loop, and it looks like we're yielding because `try_lock` failed.

**Comment by davidchisnall** [comment]
@DimitryAndric, please can you let me know if #17 fixes this for you?  It's difficult to trigger in a test because it requires contention on the lock during the initialise phase.

**Comment by DimitryAndric** [comment]
Yes, I had run my test case, i.e. part of the poppler-qt5 port, where it run a certain cmake command, in a loop for hundreds of times. I had applied:

```diff
--- a/contrib/libcxxrt/guard.cc
+++ b/contrib/libcxxrt/guard.cc
@@ -227,7 +227,7 @@ namespace
                                        // If another thread did manage to initialise this, release
                                        // the lock and notify the caller that initialisation is
                                        // done.
-                                       lock_word.store(initialised, memory_order::release);
+                                       lock_word.store(0, memory_order::release);
                                        return GuardState::InitDone;
                                }
                                return GuardState::InitLockSucceeded;
```

With the original version of libcxxrt, it would experience a hang after ~20 trial runs, but with the above diff applied it survives thousands of trial runs, without any hang.
