### ISSUE TITLE
Feature request: __cxa_init_primary_exception

### ISSUE THREAD

**Issue by itrofimow** [libcxxrt/libcxxrt#22]
Hi!

Currently, libc++ does this in `std::make_exception_ptr`:
```
try {
  throw __e;
} catch (...) {
  return current_exception();
}
```
when libstdc++ does this:
```
using _Ex2 = typename decay<_Ex>::type;
void* __e = __cxxabiv1::__cxa_allocate_exception(sizeof(_Ex));
// --------------------------------- libsupc++ extension:
(void) __cxxabiv1::__cxa_init_primary_exception(
    __e, const_cast<std::type_info*>(&typeid(_Ex)),
    __exception_ptr::__dest_thunk<_Ex2>);
// ------------------------------------------------------
__try
{
  ::new (__e) _Ex2(__ex);
  return exception_ptr(__e);
}
__catch(...)
{
  __cxxabiv1::__cxa_free_exception(__e);
  return current_exception();
}
```

The idea is that instead of going through full unwinding cycle, one could just allocate and initialize an exception directly, with `__cxa_init_primary_exception` being an extension function in libsupc++.

---------------------

`std::make_exception_ptr` is widely used with `std::promise::set_exception` in all kinds of async processing, 
and implementing it via `__cxa_init_primary_exception` not only makes it an order of magnitude faster, 
but also avoids a potential global lock, which unwinders tend to acquire (see https://isocpp.org/files/papers/P2544R0.html#problems, https://reviews.llvm.org/D130668, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71744 etc.).

I'm currently talking with developers of llibc++/ibc++abi about the same change, and if i'll manage to convince them it would be nice to have this implemented in libcxxrt as well.

The change proposed is very straightforward: 
move exception initialization from `__cxa_throw` to `__cxa_init_primary_exception`, add `[unexpected/terminate]Handler` initialization, call the new function from `__cxa__throw`.

----------------------

Does this sound reasonable to you?
Would you be willing to accept such a patch, once (hopefully) libc++/libc++api implements it as well?

**Comment by davidchisnall** [comment]
I’m not sure I fully understand the semantics of the function but the use case is definitely one that I’ve hit before. Do you have a draft implementation? I’d be happy to merge a PR that adds this if the implementation is sensible.

**Comment by itrofimow** [comment]
Hi @davidchisnall! Thank you for the quick reply.

I expect it tool look something like this: https://github.com/libcxxrt/libcxxrt/pull/23, with 
`define LIBCXXRT_HAS_INIT_PRIMARY_EXCEPTION` (or other similar name) added somewhere, so libcxx can decide whether to initialize exception directly or fallback to throw + catch.
