### ISSUE TITLE
Need an implementation of __cxa_call_terminate

### ISSUE THREAD

**Issue by bsdjhb** [libcxxrt/libcxxrt#35]
GCC 14 adds a new hook that it calls when a destructor invoked during stack unwinding throws an exception.  libcxxabi defines a similar hook named `__clang_call_terminate`.  I did a naive implementation at https://reviews.freebsd.org/D46004, but I'm not sure that is correct.

More details on this hook can be found in this GCC commit: https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=2415024e0f81f8c09bf08f947c790b43de9d0bbc

**Comment by davidchisnall** [comment]
I think your version looks correct. It’s using an exception guard, which was removed in C++17 but which we still need to support for legacy programs, so exceptions can’t escape.

**Comment by bsdjhb** [comment]
Fixed by #36
