### ISSUE TITLE
Should std::terminate be both noexcept and [[noreturn]]?

### ISSUE THREAD

**Issue by itrofimow** [libcxxrt/libcxxrt#37]
Hi!

Afaik `std::terminate` should be `noreturn` + `noexcept` since C++11, but in the libcxxrt it is neither (and for me clang refuses to compile libcxxrt against libstdc++ header).
At my work place we vendor libcxxrt and patch `std::terminate` to be `noexcept`, but don't apply `[[noreturn]]`.

Recently I've encountered what seemed to be a miscompilation, where the following code
```
void DoWork() {
	try {
		throw 42;
	} catch (...) {
		throw;
	}
}

int TryDoWork() {
	int err = 0;

	try {
		DoWork();
	} catch (const int& ex) {
		err = ex;
	} catch (...) {
		err = 1;
	}

	return err;
}

int main() {
	const auto err = TryDoWork();
	return err;
}
```
aborts due to uncaught exception coming from rethrow in `DoWork`, and the reason for that is incorrect `eh_frame->lsda->call_site_table` generated for `__cxa_rethrow` frame.

After spending some time on this I've bisected the problem down to `[[noreturn]]` attribute applied/not applied to `std::terminate`, and my reading of cppreference on `[[noreturn]]` 
```
The first declaration of the function must specify this attribute if any declaration specifies it.
If a function is declared with [[noreturn]] in one translation unit, and the same function is 
declared without [[noreturn]] in another translation unit, the program is ill-formed; no diagnostic required. 
```
suggests that currently present behavior is ill-formed; no diagnostic required when building with, say, libc++ (https://github.com/llvm/llvm-project/blob/f5ec00b79ba63eec6a39a5cc04cbdba58b0c01bf/libcxx/include/__exception/terminate.h#L19)

I can provide a reproducer for the code above aborting, but it's a bit cumbersome due to us patching libcxxrt and `-fprofile-sample-use=...` involved, which results in offsets mismatching for upstream version, so I didn't do it upfront.

**Comment by davidchisnall** [comment]
This is a tricky one. The problem is that libcxxrt is a dynamic library and so does not know which C++ standard is used in the linked program (and, indeed, it may be more than one). We aim to support C++98 up to the latest standard. 

I believe adding noexcept and noreturn should be fine. Older standards do not have these, but that means compilers for both may handle it differently.

**Comment by itrofimow** [comment]
I don't _think_ it should matter for shared library case, and for people who compile libcxxrt themselves (like we do) there already is >=C++11 requirement.

I'll create the PR with the repro linked sometime soon

**Comment by davidchisnall** [comment]
Thanks!

**Comment by itrofimow** [comment]
I've submitted a PR https://github.com/libcxxrt/libcxxrt/pull/38
