### ISSUE TITLE
Feature request: diagnostic messsage on uncaught exception

### ISSUE THREAD

**Issue by emaste** [libcxxrt/libcxxrt#39]
When aborting due to an uncaught exception other C++ ABI implementations emit a diagnostic message; it would be nice to do the same here.

libstdc++ / libsupc++ on Debian 12:

terminate called after throwing an instance of 'char const*'
Aborted

libc++abi on macOS:

libc++abi: terminating with uncaught exception of type char const*
Abort trap: 6

libcxxrt on FreeBSD:

Abort trap (core dumped)

See also [FreeBSD bug report 235033](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235033).

**Comment by emaste** [comment]
See libc++abi's [demangling_terminate_handler](https://github.com/llvm/llvm-project/blob/main/libcxxabi/src/cxa_default_handlers.cpp) for example

**Comment by davidchisnall** [comment]
Huh, I thought we [had one of those](https://github.com/libcxxrt/libcxxrt/blob/76435c4451aeb5e04e9500b090293347a38cef8d/src/exception.cc#L735).

**Comment by davidchisnall** [comment]
Hmm, I see.  We invoke this only if std::terminate returns.  We should do it if the terminate handler is the default, or possibly before calling `std::terminate`?

**Comment by emaste** [comment]
It looks like the approach in libsupc++ and libcxxabi is to have this functionality in the default `std::terminate`. I don't think we want to do it unconditionally before calling `std::terminate` but I guess it doesn't matter too much if we do it before calling std::terminate if that is the default, or if we do it in a default `std::terminate`.

I do like the approach in libcxxabi though. There's a `demangling_terminate_handler` that checks if it is handling an uncaught exception and prints the diagnostic if so. Function `set_terminate` can be used to set an alternate handler.

There's a compile-time option (`LIBCXXABI_SILENT_TERMINATE`) to chose between providing `demangling_terminate_handler` and just ::abort.
